---
- name: include variable overrides
  include_vars: "{{ item }}"
  vars:
    params:
      - "vars/{{ ansible_distribution | lower }}-{{ ansible_distribution_release | lower }}.yml"
      - "vars/{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
      - "vars/{{ ansible_distribution | lower }}.yml"
      - "vars/{{ ansible_os_family | lower }}.yml"
      - "vars/default.yml"
  loop: "{{ q('first_found', params, skip=True) }}"
  tags:
    - always

- name: install barman packages
  become: yes
  package:
    name: "{{ barman_package_names | default(barman_package_names_default) }}"
    state: "{{ barman_package_state }}"
